--- 
abstract: ~
author: 
  - Adam Kennedy <adamk@cpan.org>, L<http://ali.as/>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task
no_index: 
  directory: 
    - inc
    - t
version: 1.02
