name: Task
version: 1.01
abstract: The successor to Bundle:: for installing sets of modules
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
